
export const metadata = {
  title: "Hobbycue about",
  description: "Generated by create next app",
};const page = () => {
  return (
    <div>
      <h2>About Page</h2>
    </div>
  );
};

export default page;
