import { Poppins } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Image from "next/image";
const poppins = Poppins({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Hobbycue",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="container-fluid  min-vh-100">
          <header className="row bg-primary text-white">
            <Header />
          </header>

          {/* <main className="flex-grow-1">
            <div className="col-12">
              <div className="p-3">{children}</div>
            </div>
          </main> */}
          {children}
          <footer className="row mt-auto">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
